### PR TITLE
Update JetBrains marketplace description

### PR DESCRIPTION
**Pull request by jmertic**
Aligns with trademark and branding guidelines from the Open Mainframe Project.

### CODE REVIEW

**Comment by KUGDev** [comment]
Hello @jmertic 
Thank you for the PR
Could you please change the target branch to 1.2.1-221, as it is the next version to release
I believe, there is nothing to do with the current released version, only if there is a strong need to change these things

**Comment by jmertic** [comment]
Sure thing - done now. Thanks!

**Comment by KUGDev** [comment]
Great, thank you @jmertic 
Also, I've noticed that we use a lot of trademarks in the description
Should we mark every of them with the ™ or is it enough to have them marked at the beginning only?

**Comment by jmertic** [comment]
Good question, @KUGDev - generally, you only need to attribute the trademark on the first or most prominent usage. I went through and confirmed that now, along with cleaning up a few brand usage bits.

**Comment by KUGDev** [comment]
Merged, thank you!

**Pull request merged**
